Peter's solutions
Bobowski/python-intro pull request #1
Opened 2016-11-17 17:24 UTC by thompson2908

Here are mine solutions of basic Python's problems.

2016-11-17 17:31 UTC, Bobowski commented on introduction/examples/thompson/factorials.py
> +#         if i != 0:
Funkcja `range` może przyjąć argument od którego zacznie iterację (popatrz w dokumentacji).
Dzięki temu nie trzeba będzie sprawdzać tego warunku

2016-11-17 17:37 UTC, thompson2908 commented on introduction/examples/thompson/factorials.py
> +#         if i != 0:
```
    b = 1
    for i in range(1, a + 1):
        b = b * i
    return b
```
Link do źródła:
http://pythoncentral.io/pythons-range-function-explained/

2016-11-17 18:26 UTC, Bobowski requested changes
Ogólnie jest świetnie, ale jako, że Python to Python to trzeba poużywać trochę jego charakterystycznych rozwiązań.

2016-11-17 18:26 UTC, Bobowski commented on introduction/examples/thompson/most_used.py
> +        data = myfile.read().replace('\n', ' ')
Bardzo dobry pomysł z zamienieniem znaków nowej linii na spacje, tylko ja bym proponował zrobienie tego w kolejnej, osobnej linii. Tak dla czytelności.

2016-11-17 18:26 UTC, Bobowski commented on introduction/examples/thompson/most_used.py
> +    dict = Counter(words)
nazwa zmiennej dict przysłania konstruktor słownika `dict()` lepiej jest unikać takich zagrywek, czyli nie nazywać zmiennych tak jak nazwy funkcji wbudowanych (`build-in functions`)

2016-11-17 18:26 UTC, Bobowski commented on introduction/examples/thompson/most_used.py
> +    sorted_dict = sorted(dict.items(), key=operator.itemgetter(1), reverse=True)
Fajne rozwiązanie `key=operator.itemgetter(1)` , ja zawsze pisałem własne funkcje `lambda` aby definiować klucz do sortowania, ale tak też jest super!

2016-11-17 18:26 UTC, Bobowski commented on introduction/examples/thompson/most_used.py
> +    while n > 0:
Zamień na pętlę `for`
Głównie chodzi o to aby w pętli na końcu nie było tych śmiesznych inkrementacji czy dekrementacji iteretorów :)

2016-11-17 18:26 UTC, Bobowski commented on introduction/examples/thompson/classroom.py
> +        if not isinstance(student_id, int) or len(self.students) >= self.capacity or student_id in self.students:
Jeżeli sprawdzasz czy argument funkcji jest odpowiedniego typu to radze robić to "osobno" wpierw sprawdzić czy jest typu `int` i jak nie to od razu zwrócić. Dopiero potem sprawdzać poprawność dziedziny danych.

2016-11-17 18:26 UTC, Bobowski commented on introduction/examples/thompson/erastothenes.py
> +    if isinstance(n, int):
Lepiej jest zastosować `if not isinstance...` i od razu wyjść z funkcji. Dzięki czemu nie tworzymy niepotrzebnych wcięć (czytelność)

2016-11-17 18:26 UTC, Bobowski commented on introduction/examples/thompson/erastothenes.py
> +            while i:
`while i` wiem, że wiesz, że wyjdziemy z pętli gdy `i == 0` ale osoba nie znająca pythona może o tym nie wiedzieć. Popraw warunek (lub przejdź wgl na pętlę `for`)

2016-11-17 18:26 UTC, Bobowski commented on introduction/examples/thompson/factorials.py
> +    while i <= n:
Uczymy się pętli `for` :)

2016-11-17 18:26 UTC, Bobowski commented on introduction/examples/thompson/fibonacci.py
> +    if isinstance(n, int):
Podobnie jak wyżej. lepiej wyjść od razu przy niespełnieniu tego warunku, tak aby nie tworzyć niepotrzebnych wcięć bo wtedy kod programu zaczyna niepotrzebnie uciekać w prawo.

2016-11-17 18:26 UTC, Bobowski commented on introduction/examples/thompson/fibonacci.py
> +                tmp = pre + post
Python jest na tyle fajny, że zamiany (swap'y) dwóch czy więcej wartości można robić w miejscu. Jest to pochodna możliwości które oferują krotki.
`pre, post = post, pre + post`

2016-11-17 18:26 UTC, Bobowski commented on introduction/examples/thompson/fibonacci.py
> +    if isinstance(n, int):
Niepotrzebne wcięcia, można sprawdzić zaprzeczenie tego warunku i od razu wyjść w ciała funkcji.

2016-11-17 18:26 UTC, Bobowski commented on introduction/examples/thompson/fibonacci.py
> +            tmp = pre + post
Podobnie jak wyżej. Można zamienić w miejscu (na razie traktuj to jako ciekawostkę)

2016-11-17 18:26 UTC, Bobowski commented on introduction/examples/thompson/fibonacci.py
> +    if n == 0:
Hint: 
```
if n == 0 or n == 1:
    return n
```

Albo (z możliwości jakie dają nam listy)
```
if n in [0, 1]:
    return n
```

2016-11-17 18:26 UTC, Bobowski commented on introduction/examples/thompson/friends.py
> +special_trades_list = list(set(friends.values()))
Takie rozwiązania to tzw _Pythonic solution_ bardzo eleganckie i proste rozwiązania danych zaganień. Świetne!

2016-11-17 18:26 UTC, Bobowski commented on introduction/examples/thompson/friends.py
> +special_trades = [e for e in friends.values() if list(friends.values()).count(e) < 2]
Proponowałbym jasne stwierdzenie `count(e) == 1`

2016-11-17 18:26 UTC, Bobowski commented on introduction/examples/thompson/friends.py
> +        friends_trades.update({person: [friends[person], "awesome"]})
Do słownika można dodawać nowe klucze również tak `friends_trades[key] = value`
Jest to preferowane rozwiązanie (nad `update`) jeżeli dodajemy po jednym kluczu na raz.

2016-11-17 18:26 UTC, Bobowski commented on introduction/examples/thompson/is_prime.py
> +def is_prime(n):
Proponuję sprawdzać negację tego warunku i wychodzić od razu z funkcji w przypadku niepowodzenia.

2016-11-19 15:29 UTC, Bobowski approved these changes

2016-11-19 15:29 UTC, merged