Zrobione :)
Bobowski/python-intro pull request #3
Opened 2016-11-23 20:58 UTC by Fadion96

Możesz spokojnie wstawić, zrobiłem te zadania typu test Millera-Rabina :)

2016-11-24 13:28 UTC, Bobowski requested changes
Jest pięknie. Jeżeli sam takie cuda piszesz to jestem bardzo szczęśliwy ;)

Popraw te `isinstance(...)` i będzie piękniej.

2016-11-24 13:28 UTC, Bobowski commented on examples/fadion/classes.py
> +            try:
Tutaj nie ma czego "próbować" (`try`) ponieważ tutaj rzucasz wyjątek a nie przechwytujesz.

2016-11-24 13:28 UTC, Bobowski commented on examples/fadion/classes.py
> +            except AlreadyInClassroomException as e:
Jak wyżej :)

2016-11-24 13:28 UTC, Bobowski commented on examples/fadion/classes.py
> +        del self.students[student.uid]
Nawiasy? Tzn nie wiem sam czy potrzeba czy też nie. Możesz mi przy okazji odpowiedzieć na to pytanie :)

2016-11-24 13:28 UTC, Bobowski commented on examples/fadion/factorial.py
> +    if isinstance(x, int) and x > -1:
Osobiście polecam sprawdzanie `isintance()` w osobnym `if`ie i na początku funkcji, 
``` python
if not isinstance(...):
    return False
```

2016-11-30 09:58 UTC, Fadion96 commented on examples/fadion/classes.py
> +        del self.students[student.uid]
Sprawdziłem w dokumentacji i nawiasy nie są potrzebne przy del ponieważ jest to wyrażenie.
Tak samo jak do wersji 2.7 można było używać wyrażenia print, co w nowszych wersjach zostało zastąpione funkcją print()

2016-11-30 14:10 UTC, Bobowski commented on examples/fadion/factorial.py
> -    if isinstance(x, int) and x > -1:
A co jakby rozbić to na dwa sprawdzenia warunku?
``` python
if not isinstance(x, int):
    return False

if x < 0:
    return False
```

Czy takie rozbicie nie dodaje czytelności ?

2016-11-30 14:30 UTC, merged